---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: "tykio/tyk-build-env"
inputs:
  - name: gw
run:
  path: bash
  args:
    - -exc
    - |
      #cd gw && make test
      true

params:
    GOPATH: /go
